version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.5.0.0
    container_name: etlplus-oracle-db
    environment:
      # Oracle Free requires these environment variables
      ORACLE_PWD: etlplus123
      ORACLE_CHARACTERSET: AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager Express
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle-init:/opt/oracle/scripts/setup
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    networks:
      - etlplus-network

volumes:
  oracle_data:
    driver: local

networks:
  etlplus-network:
    driver: bridge
