name: 🛡️ Security Audit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # Weekly on Monday at 3 AM

jobs:
  security-audit:
    name: 🔒 Security Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔍 Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: 📊 Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: 🐳 Build Docker image for scanning
      run: |
        docker build -t etlplus:security-scan .

    - name: 🔍 Scan Docker image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'etlplus:security-scan'
        format: 'sarif'
        output: 'trivy-docker-results.sarif'

    - name: 📊 Upload Docker scan results
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-docker-results.sarif'

    - name: 🔐 Secret scanning with TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD
        extra_args: --debug --only-verified

  dependency-review:
    name: 📦 Dependency Review
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 🔍 Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate

  sbom-generation:
    name: 📋 SBOM Generation
    runs-on: ubuntu-latest
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4

    - name: 📋 Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        path: ./
        format: spdx-json

    - name: 📤 Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: sbom
        path: ./sbom.spdx.json
